apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: cicd-user-cluster-role-binding
subjects:
- kind: User # for example only . It should be a group
  name: cicd-user@my-gkeproject-1.iam.gserviceaccount.com # Name is case sensitive. Name of user or group
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cicd-user-cluster-role
  apiGroup: rbac.authorization.k8s.io
