kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-admin-binding
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User # for example only . It should be a group
  name: sa-admin-user@amex-sso-poc.iam.gserviceaccount.com # Name is case sensitive. Name of user or group
